---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-translator-sb-deployment
  namespace: iot-hub-gateway
  labels:
    app: gateway-translator-sb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-translator-sb
  template:
    metadata:
      labels:
        app: gateway-translator-sb
    spec:
      containers:
      - name: gateway-translator-sb
        image: REPLACE-ACR-NAME.azurecr.io/iothub/gateway-translator:latest
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: GatewayOrchestrator
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: FUNCTIONS_WORKER_RUNTIME
          value: dotnet
        - name: gateway-server-host
          value: http://gateway-server-http-service/iot-gateway
        - name: AppVersion
          value: v1.0
        envFrom:
        - secretRef:
            name: gateway-translator
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 512Mi
              cpu: 500m
      serviceAccountName: gateway-translator-svc-act
---