---
# Secrets can be created via your selected devops platform or retrieved from Azure Key Vault at runtime
apiVersion: v1
kind: Secret
metadata:
  name: gateway-translator
  namespace: iot-hub-gateway
data:
  gateway-translator-sb-conn: REPLACE_BASE64
---
# Below secrets can be used for Azure Function Authentication
# apiVersion: v1
# kind: Secret
# metadata:
#   name: func-keys-kube-secret-gateway-translator
#   namespace: iot-hub-gateway
# data:
#   host.master: BASE64=
#   host.function.default: BASE64=
#   host.systemKey.default: BASE64=
#   functions.gatewayorchestrator.default: BASE64=
# ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-translator-svc-act
  namespace: iot-hub-gateway
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keys-manager-role
  namespace: iot-hub-gateway
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-translator-svc-act-keys-manager-rolebinding
  namespace: iot-hub-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keys-manager-role
subjects:
- kind: ServiceAccount
  name: gateway-translator-svc-act
---