apiVersion: apps/v1
kind: Deployment
metadata:
  name: iothub-gateway-server-deployment
  labels:
    app: iothub-gateway-server
spec:
  replicas: 5
  selector:
    matchLabels:
      app: iothub-gateway-server
  template:
    metadata:
      labels:
        app: iothub-gateway-server
    spec:
      containers:
      - name: iothub-gateway-server
        image: REPLACE-ACR-NAME.azurecr.io/iothub/iothub-gateway-server:1.0.2
        env:
        - name: IoTHubHostName
          value: REPLACE-IOTHUB-NAME.azure-devices.net
        - name: AccessPolicyName
          value: REPLACE-POLICY-NAME
        - name: AccessPolicyKey
          value: "REPLACE-POLICY-KEY"
        - name: SharedAccessPolicyKeyEnabled
          value: "true"
        - name: DirectMethodEnabled
          value: "true"
        - name: CloudMessagesEnabled
          value: "true"
        #- name: SQL_USER
         # valueFrom:
          #  secretKeyRef:
            #  name: sqlusersecret
            #  key: sqluser
        ports:
        - containerPort: 80
        # readinessProbe:
        #   httpGet:
        #     path: /api
        #     port: 80
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        resources:
            limits:
              memory: 1Gi
              cpu: 1000m
            requests:
              memory: 1Gi
              cpu: 1000m
      dnsPolicy: ClusterFirst