apiVersion: v1
kind: Secret
metadata:
  name: gateway-orchestrator
data:
  AzureWebJobsStorage: VXNlRGV2ZWxvcG1lbnRTdG9yYWdlPXRydWU=
  FUNCTIONS_WORKER_RUNTIME: ZG90bmV0
  gateway-orchestrator-sb-conn: BASE64
---
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-gateway-orchestrator
data:
  host.master: BASE64=
  host.function.default: BASE64=
  host.systemKey.default: BASE64=
  functions.gatewayorchestrator.default: BASE64=
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-orchestrator-function-keys-identity-svc-act
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-orchestrator-function-keys-identity-svc-act-functions-keys-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: gateway-orchestrator-function-keys-identity-svc-act
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-orchestrator-http
spec:
  selector:
    app: gateway-orchestrator-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-orchestrator-http
  labels:
    app: gateway-orchestrator-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-orchestrator-http
  template:
    metadata:
      labels:
        app: gateway-orchestrator-http
    spec:
      containers:
      - name: gateway-orchestrator-http
        image: CONTAINER-REGISTRY-URL/gateway-orchestrator:latest
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: GatewayOrchestrator
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-gateway-orchestrator
        envFrom:
        - secretRef:
            name: gateway-orchestrator
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: gateway-orchestrator-function-keys-identity-svc-act
---

