version: '3.4'

services:
  gateway-translator:
    image: ${DOCKER_REGISTRY-}gateway-translator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5100:80"
      - "50002:50002"
    environment:
      - DAPR_GRPC_PORT=50002
    depends_on:
      - redis
      - placement
    networks:
      - gateway-dapr
  gateway-translator-dapr:
    image: "daprio/daprd:1.2.0"
    command: ["./daprd",
     "-app-id", "gateway-translator",
     "-app-port", "80",
     "-metrics-port", "9091",
     "-log-level", "debug",
     "-config", "components/dapr-config.yaml",
     "-placement-host-address", "placement:50006",
     "-dapr-grpc-port", "50002",
     "-components-path", "/components"]
    volumes:
        - "./DaprComponentsDev:/components"
        - "./certificates/:/certificates"
    depends_on:
      - gateway-translator
    network_mode: "service:gateway-translator"

  placement:
    image: "daprio/dapr:1.2.0"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - gateway-dapr

  zipkin: 
    image: "openzipkin/zipkin"
    ports:
    - "9412:9411"
    networks:
      - gateway-dapr

  redis:
    image: "redis"
    ports:
      - "6380:6379"
    networks:
      - gateway-dapr

networks:
  gateway-dapr: