apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: gateway-servicebus
  namespace: iot-hub-gateway
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString # Required
    secretKeyRef:
      name: gateway-orchestrator
      key: connectionString
  - name: timeoutInSec # Optional
    value: 60
  - name: timeoutInSec # Optional
    value: 60
  - name: handlerTimeoutInSec # Optional
    value: 60
  - name: disableEntityManagement # Optional
    value: "true"
  - name: maxDeliveryCount # Optional
    value: 10
  - name: lockDurationInSec # Optional
    value: 60
  - name: lockRenewalInSec # Optional
    value: 20
  - name: maxActiveMessages # Optional
    value: 2000
  - name: maxActiveMessagesRecoveryInSec # Optional
    value: 2
  - name: maxConcurrentHandlers # Optional
    value: 10
  - name: prefetchCount # Optional
    value: 5
  - name: defaultMessageTimeToLiveInSec # Optional
    value: 3600
  #- name: autoDeleteOnIdleInSec # Optional
  #  value: 36000
  - name: maxReconnectionAttempts # Optional
    value: 30
  - name: connectionRecoveryInSec # Optional
    value: 2
  - name: publishMaxRetries # Optional
    value: 5
  - name: publishInitialRetryInternalInMs # Optional
    value: 500
auth:
  secretStore: kubernetes