---
# Secrets can be created via your selected devops platform or retrieved from Azure Key Vault at runtime
apiVersion: v1
kind: Secret
metadata:
  name: gateway-orchestrator
  namespace: iot-hub-gateway
type: Opaque
data:
  connectionString: REPLACE_BASE64
  APPINSIGHTS_CONNECTIONSTRING: REPLACE_BASE64
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-orchestrator-svc-act
  namespace: iot-hub-gateway
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keys-manager-role
  namespace: iot-hub-gateway
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-orchestrator-svc-act-keys-manager-rolebinding
  namespace: iot-hub-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keys-manager-role
subjects:
- kind: ServiceAccount
  name: gateway-orchestrator-svc-act
#---
#kind: RoleBinding
#apiVersion: rbac.authorization.k8s.io/v1
#metadata:
#  name: dapr-secret-reader
#  namespace: iot-hub-gateway
#subjects:
#- kind: ServiceAccount
#  name: default
#  namespace: default
#roleRef:
#  kind: Role
#  name: keys-manager-role
#  apiGroup: rbac.authorization.k8s.io