---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-orchestrator-http-deployment
  namespace: iot-hub-gateway
  labels:
    app: gateway-orchestrator-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-orchestrator-http
  template:
    metadata:
      labels:
        app: gateway-orchestrator-http
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "gateway-orchestrator"
        dapr.io/app-port: "80"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: gateway-orchestrator-http
        image: REPLACE.azurecr.io/iothub/gateway-orchestrator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: AppVersion
          value: v2.0
        envFrom:
        - configMapRef:
            name: gateway-orchestrator-cm
        - secretRef:
            name: gateway-orchestrator
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
        resources:
            limits:
              memory: 4Gi
              cpu: 1000m
            requests:
              memory: 4Gi
              cpu: 1000m
      serviceAccountName: gateway-orchestrator-svc-act