apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: gateway-orchestrator-http-deployment-cpu-scaledobject
  namespace: iot-hub-gateway
spec:
  scaleTargetRef:
    name: gateway-orchestrator-http-deployment
  pollingInterval: 30  # Optional. Default: 30 seconds
  cooldownPeriod:  300 # Optional. Default: 300 seconds
  minReplicaCount: 1   # Optional. Default: 0
  maxReplicaCount: 15 # Optional. Default: 100
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "70"
